version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: monthly
    time: "11:00"
    timezone: Asia/Tokyo
  open-pull-requests-limit: 20
  reviewers:
  - amatotsuji
  - yuta-sanada0089
  allow:
  - dependency-type: direct
  - dependency-type: indirect
  ignore:
  - dependency-name: codecov
    versions:
    - ">= 0.2.14.a, < 0.2.15"
  - dependency-name: aws-partitions
    versions:
    - 1.431.0
    - 1.433.0
    - 1.437.0
    - 1.448.0
  - dependency-name: codecov
    versions:
    - 0.5.2
  - dependency-name: lita
    versions:
    - 4.8.0
  - dependency-name: aws-eventstream
    versions:
    - 1.1.1
  - dependency-name: aws-sigv4
    versions:
    - 1.2.3
